#!/usr/bin/perl -w

use strict;

my $secret = int(1+rand 100);
while(1){
	print "Input a number : ($secret)  \n";
	chomp(my $guess = <STDIN>);
	if($guess =~ /quit|exit|\A\s*\z/){
		last;
	}
	$guess > $secret ? print "Too hight!\n" : $guess < $secret ? print "Too low!\n" : ((print "It is $guess, secret is $secret!\n") && last);
}
print "Quit!\n";

