#!/usr/bin/perl -w

use strict;

use 5.010;

sub divisors{
	my $number = shift;
	my @divisors = ();
	foreach my $divisor(2 ... ($number/2)){
		push @divisors,$divisor unless $number % $divisor;
	}
	return @divisors;
}

given($ARGV[0]){
	when(not /\A\d+\z/) {say "Param Error!"}
	my @empty;
	my @divisors = &divisors($_);
	when(@divisors ~~ @empty) {say "Prime!";}
	default { say "$_ is by @divisors";}
}
