#!/usr/bin/perl -w

use strict;
use 5.010;

my $secret = int(1+rand 100);
while(1){
	print "Input a number : ($secret)  \n";
	chomp(my $guess = <STDIN>);
	given($guess){
		when(/quit|exit|\A\s*\z/){last;}
		when(!/\A\d+\z/) {last;}
		when($_ > $secret) {say "Too hight!";}
		when($_ < $secret) {say "Too low!";}
		default {say "Just $_!"; last}
	}
}
print "Quit!\n";

