#!/usr/bin/perl -w

use strict;

use 5.010001;

say "Input a Number:";
chomp(my $number = <STDIN>);
given($number){
	when(!/\A\d+\z/){say "Error"}
	when(!($_ % 3)) {say "Fizz";continue}
	when(!($_ % 5)) {say "Bin";continue}
	when(!($_ % 7)) {say "Sausage"}
}
