#!/usr/bin/perl -w

use strict;

print "Enter a string and a number \n";
print "String : ";
my $string = <STDIN>;
print "Number : ";
chomp(my $number = <STDIN>);
my $result = $string x $number;
print $result;
