#!/usr/bin/perl -w
##Copyright (C) 2014 by Ryuhkohchin


use strict;

print "Enter two numbers : \nfirst: ";
chomp(my $number_1 = <STDIN>);
print "second : ";
chomp(my $number_2 = <STDIN>);
my $result = $number_1 * $number_2;
print "result of $number_1 * $number_2 : $result\n";
