#!/usr/bin/perl -w

use strict;

print "Enter the ratio : \n";
my $PI = 3.141592654;
chomp(my $ratio = <STDIN>);
my $perimeter = 0;
if($ratio > 0){
	$perimeter = $ratio * $PI * 2;
}
print "perimeter : $perimeter\n";
