#!/usr/bin/perl -w
##Copyright (C) 2014 by Ryuhkohchin


use strict;

chomp(my @lines=<STDIN>);
print "@lines\n";
my @lines_sort = sort @lines;
print "@lines_sort\n";
foreach(@lines_sort){
	print "$_\n";
}
