#!/usr/bin/perl -w

use strict;

sub total{
	my @numbers = @_;
	my $sum = 0;
	foreach(@numbers){
		$sum += $_;
	}
	$sum
}

my @fred = qw{1 3 5 7 9};
my $fred_total = total(@fred);
print "The total of \@fred is $fred_total.\n";
print "Enter some number on separate lines: ";
my $user_total = total(<STDIN>);
print "The total of those number is $user_total.\n";
