#!/usr/bin/perl -w

use strict;

sub average{
	my $sum = 0;
	my $num = @_;
	foreach(@_){
		$sum += $_;
	}
	$sum/$num
}

sub above_average{
	my $ave = average(@_);
	my @result;
	my @numbers = @_;
	foreach(@_){
		if($_ > $ave){
			push @result,$_;
		}
	}
	@result
}

my @fred = above_average(1...10);
print "\@fred is @fred\n";
print "(Should be 6 7 8 9 10)\n";
my @barney = above_average(100,1...10);
print "\@barney is @barney\n";
print "(Should be just 100)\n";
