#!/usr/bin/perl -w

use 5.010;

sub greet{
	state @for_guest;
	if(@for_guest){
		print "Hi $_[0]! I've seen: @for_guest\n";
	}else{
		print "Hi $_[0]! You are the first one here!\n";
	}
	push @for_guest,$_[0]
}

greet("Fred");
greet("Barney");
greet("Wilma");
greet("Betty");
