#!/usr/bin/perl -w
##Copyright (C) 2014 by Ryuhkohchin

use strict;

print "Enter something end with CTRL+D\n";
chomp(my @lines = <>);
print "Enter shiftwidth : \n";
chomp(my $num = <>);
print "1234567890" x 6 , "\n";
foreach (@lines){
	printf("%${num}s\n",$_);
}
