#!/usr/bin/perl -w
##Copyright (C) 2014 by Ryuhkohchin


use strict;

while(<>){
	chomp;
	if(/(\b\w*a)\b/){
		print "Matched! |$`<$&>$'|\n";
		print "\$1 contains $1\n";
	}else{
		print "No match : |$_|\n";
	}
}
