#!/usr/bin/perl -w
##Copyright (C) 2014 by Ryuhkohchin


use strict;

while(<>){
	chomp;
	if(/(\b\w*a\b)(.{0,5})/){
		print "Matched! |$`<$&>$'|\n";
		print "$1$2\n";	
	}else{
		print "No match : |$_|\n";
	}
}
