#!/usr/bin/perl -w

use strict;

print "Which dir do you wanna process?\n";
chomp(my $dir = <STDIN>);
if($dir =~ /\A\s*\z/){
	chdir or die "Cannot change dir : $!";
}else{
	chdir $dir or die "Cant change dir : $!";
}
opendir my $dh,"." or die "Cant open dir : $!";
foreach my $name(sort readdir $dh){
	print "$name\n";
}
closedir $dh;
