#!/usr/bin/perl -w

use strict;

print "Which dir do you wanna process?\n";
chomp(my $dir = <STDIN>);
if($dir =~ /\A\s*\z/){
	chdir or die "Cannot change dir : $!";
}else{
	chdir $dir or die "Cant change dir : $!";
}
my @names = <.* *>;
foreach (sort @names){
	print "$_\n";
}

